package be.ugent.mmlab.rml.model.RDFTerm;

import java.util.Set;

import org.eclipse.rdf4j.model.IRI;

/**
 * ************************************************************************
 * <p>
 * RML - Model : Subject Map Interface
 * <p>
 * A Subject Map is a Term Map which generates the subject
 * of the RDF triples generated by a particular Triples Map.
 *
 * @author andimou
 * <p>
 * **************************************************************************
 */
public interface SubjectMap extends TermMap {

    /**
     * A Subject Map may have one or more class IRIs.
     *
     * @return Set<URI>
     */
    Set<IRI> getClassIRIs();

    /**
     * @param uri
     */
    void setClassIRIs(Set<IRI> uri);

    /**
     * A Subject Map may have one or more associated Graph Maps.
     *
     * @return Set<GraphMap>
     */
    Set<GraphMap> getGraphMaps();

    /**
     * @param graphMap
     */
    void setGraphMaps(Set<GraphMap> graphMap);

}
